import generatePayload from 'promptpay-qr';
import { QRCodeCanvas } from 'qrcode.react';

export default function ReceiptSlip({ billing, config }: { billing: any, config: any }) {
    const promptPayPayload = config.promptPayId
        ? generatePayload(config.promptPayId, { amount: billing.totalAmount })
        : "";

    return (
        <div className="w-[80mm] bg-white p-4 mx-auto text-black font-mono text-sm">
            {/* Header */}
            <div className="text-center mb-6 border-b border-dashed border-gray-300 pb-4">
                <h1 className="font-bold text-lg">{config.dormName}</h1>
                <p className="text-xs text-gray-500 mt-1 whitespace-pre-line">{config.dormAddress}</p>
                <div className="mt-2 text-xs">
                    INV: #{billing.id.toString().padStart(6, '0')}<br />
                    Date: {new Date(billing.createdAt).toLocaleDateString('th-TH')}
                </div>
            </div>

            {/* Customer */}
            <div className="mb-4 text-center">
                <span className="font-bold text-lg">Room {billing.room.number}</span>
                <p className="text-xs text-gray-500">{billing.resident?.fullName || "Guest"}</p>
            </div>

            {/* Items */}
            <div className="space-y-1 mb-4">
                <div className="flex justify-between">
                    <span>Rent</span>
                    <span>{billing.rentAmount.toLocaleString()}</span>
                </div>
                <div className="flex justify-between">
                    <span>Water ({billing.waterUsage}u)</span>
                    <span>{billing.waterAmount.toLocaleString()}</span>
                </div>
                <div className="flex justify-between">
                    <span>Elec ({billing.electricUsage}u)</span>
                    <span>{billing.electricAmount.toLocaleString()}</span>
                </div>
                {billing.trashAmount > 0 && (
                    <div className="flex justify-between">
                        <span>Trash</span>
                        <span>{billing.trashAmount.toLocaleString()}</span>
                    </div>
                )}
                {billing.otherAmount > 0 && (
                    <div className="flex justify-between">
                        <span>Other</span>
                        <span>{billing.otherAmount.toLocaleString()}</span>
                    </div>
                )}
            </div>

            {/* Total */}
            <div className="border-t-2 border-black pt-2 mb-6">
                <div className="flex justify-between items-center font-bold text-lg">
                    <span>TOTAL</span>
                    <span>฿{billing.totalAmount.toLocaleString()}</span>
                </div>
            </div>

            {/* QR Code */}
            {promptPayPayload && (
                <div className="text-center mb-6">
                    <div className="inline-block bg-white p-2 border border-black rounded-lg">
                        <QRCodeCanvas value={promptPayPayload} size={150} />
                    </div>
                    <p className="text-xs font-bold mt-2">SCAN TO PAY</p>
                    <p className="text-[10px] text-gray-500">{config.bankAccountName}</p>
                </div>
            )}

            <div className="text-center text-[10px] text-gray-400">
                Generated by StaySync
            </div>
        </div>
    );
}
