"use client";

import generatePayload from 'promptpay-qr';
import { QRCodeCanvas } from 'qrcode.react';

export default function ReceiptSlip({ billing, resident, config }: { billing: any, resident: any, config: any }) {
    // Calculate Amounts safely
    const waterAmount = (billing.waterMeterCurrent - billing.waterMeterLast) * billing.waterRate;
    const electricAmount = (billing.electricMeterCurrent - billing.electricMeterLast) * billing.electricRate;
    const rentAmount = billing.totalAmount - (waterAmount + electricAmount + (billing.trashFee || 0) + (billing.otherFees || 0) + (billing.internetFee || 0));

    const promptPayPayload = config.promptPayId
        ? generatePayload(config.promptPayId, { amount: billing.totalAmount })
        : "";

    return (
        <div className="w-[80mm] bg-white p-4 mx-auto text-black font-mono text-sm">
            {/* Header */}
            <div className="text-center mb-6 border-b border-dashed border-gray-300 pb-4">
                {config.invoiceLogo && (
                    <img src={config.invoiceLogo} alt="Logo" className="h-8 w-auto object-contain mx-auto mb-2 grayscale" />
                )}
                <h1 className="font-bold text-lg">{config.dormName}</h1>
                <p className="text-xs text-gray-500 mt-1 whitespace-pre-line">{config.dormAddress}</p>
                <div className="mt-2 text-xs">
                    INV: #{billing.id.toString().padStart(6, '0')}<br />
                    Date: {new Date(billing.createdAt).toLocaleDateString('th-TH')}
                </div>
            </div>

            {/* Customer */}
            <div className="mb-4 text-center">
                <span className="font-bold text-lg">Room {billing.room.number}</span>
                <p className="text-xs text-gray-500">{resident?.fullName || "Guest"}</p>
            </div>

            {/* Items */}
            <div className="space-y-1 mb-4">
                <div className="flex justify-between">
                    <span>Rent</span>
                    <span>{rentAmount.toLocaleString()}</span>
                </div>
                <div className="flex justify-between">
                    <span>Water ({(billing.waterMeterCurrent - billing.waterMeterLast).toLocaleString()}u)</span>
                    <span>{waterAmount.toLocaleString()}</span>
                </div>
                <div className="flex justify-between">
                    <span>Elec ({(billing.electricMeterCurrent - billing.electricMeterLast).toLocaleString()}u)</span>
                    <span>{electricAmount.toLocaleString()}</span>
                </div>
                {billing.trashFee > 0 && (
                    <div className="flex justify-between">
                        <span>Trash</span>
                        <span>{billing.trashFee.toLocaleString()}</span>
                    </div>
                )}
                {billing.otherFees > 0 && (
                    <div className="flex justify-between">
                        <span>Other</span>
                        <span>{billing.otherFees.toLocaleString()}</span>
                    </div>
                )}
                {billing.internetFee > 0 && (
                    <div className="flex justify-between">
                        <span>Internet</span>
                        <span>{billing.internetFee.toLocaleString()}</span>
                    </div>
                )}
            </div>

            {/* Total */}
            <div className="border-t-2 border-black pt-2 mb-6">
                <div className="flex justify-between items-center font-bold text-lg">
                    <span>TOTAL</span>
                    <span>฿{billing.totalAmount.toLocaleString()}</span>
                </div>
            </div>

            {/* QR Code */}
            {promptPayPayload && (
                <div className="text-center mb-6">
                    <div className="inline-block bg-white p-2 border border-black rounded-lg">
                        <QRCodeCanvas value={promptPayPayload} size={150} />
                    </div>
                    <p className="text-xs font-bold mt-2">SCAN TO PAY</p>
                    <p className="text-[10px] text-gray-500">{config.bankAccountName}</p>
                </div>
            )}

            {config.invoiceNote && (
                <div className="text-center text-xs mb-4 border-t border-dashed border-gray-300 pt-2 italic">
                    {config.invoiceNote}
                </div>
            )}

            <div className="text-center text-[10px] text-gray-400">
                Generated by StaySync
            </div>
        </div>
    );
}
