@echo off
echo Killing git processes...
taskkill /F /IM git.exe
echo Removing lock files...
if exist .git\index.lock del .git\index.lock
echo Git Status...
git status
echo Adding files...
git add .
echo Committing...
git commit -m "fix: Resolve MobileNav link import error"
echo Pushing...
git push origin master
echo Done!
